name: Lobby
main: net.craftions.lobby.Lobby
version: ${project.version}
api-version: 1.16
commands:
  setspawn:
    permission: craftions.lobby.command.setspawn
    usage: /lobby
  spawn:
    usage: /spawn